# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    env:
      platform: azure
      region: us-east
      account: 0987654321
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "¡Hola mundo!"

      - name: "Mostrando variables de entorno"
        if: ${{env.platform == 'azure'}}
        run: |
          echo "Valor Platform: ${{env.platform}}"
          echo "Valor Region: ${{env.region}}"
          echo "Valor Account: ${{env.account}}"
      - name: "Mostrando variables de entorno"
        if: ${{env.platform != 'azure'}}
        run: |
          echo "Plataforma inválida"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Github_Actor: ${{github.actor}}"
          echo "Github_Repository: ${{github.repository}}"
          echo "Evento: ${{toJSON(github.event)}}"